package com.docufind.app.ui.navigation

object DocuFindRoutes {
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val PROFILE_SETUP = "profile_setup"
    const val PIN_SETUP = "pin_setup"
    const val BIOMETRIC_SETUP = "biometric_setup"
    const val MAIN = "main"

    const val HOME = "home"
    const val SEARCH = "search"
    const val ADD = "add"
    const val REMINDERS = "reminders"
    const val SETTINGS = "settings"
    const val PRIVACY = "privacy"
    const val BACKUP = "backup"
    const val STORAGE = "storage"
    const val SECURITY = "security"
    const val TRASH = "trash"
    const val ACTIVITY_INSIGHTS = "activity_insights"
    const val HOW_TO_USE = "how_to_use"
    const val HELP_SUPPORT = "help_support"
    const val REPORT_BUG = "report_bug"
    const val SEND_FEEDBACK = "send_feedback"
    const val ABOUT = "about"
    const val VAULT = "vault"
    const val CATEGORY = "category/{categoryId}"
    const val RECORD_DETAIL = "record/{recordId}"
    const val FAMILY_DETAIL = "family/{memberId}"
    const val EMERGENCY_CONTACTS = "emergency_contacts"
    const val PET_DETAIL = "pet/{petId}"
    const val FILE_PREVIEW = "file_preview/{fileId}"
    const val SCAN_QR = "scan_qr"

    fun category(categoryId: String) = "category/$categoryId"
    fun recordDetail(recordId: String) = "record/$recordId"
    fun familyDetail(memberId: String) = "family/$memberId"
    fun petDetail(petId: String) = "pet/$petId"
    fun filePreview(fileId: String) = "file_preview/$fileId"
}
