package com.docufind.app.domain.model

import androidx.compose.ui.graphics.Color
import kotlin.random.Random

object HomeTaglines {
    val accentPalette: List<Color> = listOf(
        Color(0xFF1E88E5),
        Color(0xFF3949AB),
        Color(0xFF00897B),
        Color(0xFF43A047),
        Color(0xFFE91E63),
        Color(0xFFFB8C00),
        Color(0xFF8E24AA),
        Color(0xFF00ACC1),
        Color(0xFF5E35B1),
        Color(0xFFD32F2F),
        Color(0xFF1565C0),
        Color(0xFF6D4C41)
    )

    val taglines: List<String> = listOf(
        "Everything important, safe in one place.",
        "Your documents, always within reach.",
        "Find what matters, when it matters.",
        "Private records. Simple access.",
        "Your life records, beautifully organized.",
        "Store smart. Find faster.",
        "Important papers, never lost again.",
        "Your secure home for documents.",
        "Keep documents ready for life.",
        "Secure today, stress less tomorrow.",
        "Organize once, find forever.",
        "Your private vault, always close.",
        "Documents protected, reminders ready.",
        "Life records made simple.",
        "One app for every important record.",
        "From IDs to insurance, stay prepared.",
        "Your family records, safely organized.",
        "Your documents stay on your device.",
        "Search less, live more.",
        "Never miss an important renewal.",
        "Your records, your control.",
        "Keep it safe. Find it fast.",
        "A smarter way to store documents.",
        "Your secure document companion.",
        "Every record, one safe place.",
        "Peace of mind for important papers.",
        "Private by design, simple by choice.",
        "Local storage. Total control.",
        "Store documents without cloud worries.",
        "Important dates, always remembered.",
        "Your vault for everyday life.",
        "Find documents in seconds.",
        "Keep records ready for emergencies.",
        "Your personal document locker.",
        "Safe records for your family.",
        "Smart reminders for real life.",
        "All your documents, neatly arranged.",
        "Protect what matters most.",
        "Because every document matters.",
        "Your privacy comes first.",
        "No cloud. No confusion. Just control.",
        "Your important files, organized safely.",
        "One secure space for life records.",
        "Save today, find anytime.",
        "A better way to manage records.",
        "Your documents, your rules.",
        "Simple storage for important lives.",
        "Vault your records, not your time.",
        "Stay ready for every renewal.",
        "A safe place for personal records.",
        "Family documents made easy.",
        "Health records, IDs and more.",
        "From passport to pet records.",
        "Never search WhatsApp for documents again.",
        "Important records deserve better.",
        "Stay organized before you need it.",
        "Built for privacy. Made for life.",
        "Your secure folder for everything important.",
        "Documents protected on your phone.",
        "Keep proof, papers and reminders together.",
        "Safe, simple and always yours.",
        "Your life, organized privately.",
        "One tap closer to your records.",
        "Documents that are easy to find.",
        "Store once. Access when needed.",
        "Records ready when life asks.",
        "Your private space for important files.",
        "Secure documents without complexity.",
        "Everything saved, nothing uploaded.",
        "Your phone, your vault.",
        "Be ready with every document.",
        "Find IDs, bills and reports quickly.",
        "Private documents, peaceful mind.",
        "Keep your family prepared.",
        "Your records, protected locally.",
        "No cloud needed to stay organized.",
        "Smarter document storage starts here.",
        "Save important details safely.",
        "Your personal records assistant.",
        "Never lose a document again.",
        "Keep certificates, IDs and reminders together.",
        "Safe access for everyday needs.",
        "Your trusted document vault.",
        "Organized records. Confident life.",
        "Protect documents from daily chaos.",
        "Your important details, one secure tap away.",
        "Documents, reminders and peace of mind.",
        "Find faster. Worry less.",
        "Your vault for family and life.",
        "Everything private, everything organized.",
        "Your secure record keeper.",
        "For documents you cannot afford to lose.",
        "Stay prepared, stay private.",
        "All important records under one roof.",
        "Simple vault for serious documents.",
        "Your data stays with you.",
        "Safe records, simple reminders.",
        "A calmer way to manage documents.",
        "Your essentials, always protected.",
        "Where important records live safely.",
        "Search smarter across your records.",
        "Private vault for modern families.",
        "Your life documents, securely managed.",
        "Everything important, always ready.",
        "Secure storage that feels simple.",
        "Your documents, protected by design.",
        "Keep life's paperwork under control.",
        "One secure app for important records.",
        "Find it. Lock it. Trust it.",
        "Everything important. Safe in one place.",
        "100% private. Everything stays on your device."
    )

    fun pickRandom(random: Random = Random.Default): Pair<String, Color> {
        val tagline = taglines[random.nextInt(taglines.size)]
        val accent = accentPalette[random.nextInt(accentPalette.size)]
        return tagline to accent
    }
}
